services:
  # Web-сервис для основного приложения
  - type: web
    name: ooo-bnal-bank
    runtime: node
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1